# Defined tags: network, upgrade-kernel
---
- name: Check ansible version
  import_playbook: ansible_version.yml

- name: Ensure compatibility with old groups
  import_playbook: legacy_groups.yml

- hosts: bastion[0]
  gather_facts: False
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults }
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"] }

- name: Gather facts
  tags: always
  import_playbook: facts.yml

# Bootstrap OS
# NTP
- name: Sync with NTP
  hosts: k8s_cluster
  gather_facts: False
  tasks:
    - command: which chronyd
      register: chronyd
      ignore_errors: true
    - command: grep '^server ntp\.aliyun\.com iburst' /etc/chrony.conf
      register: chrony_conf
      ignore_errors: true
    - name: Add NTP
      lineinfile:
        dest: /etc/chrony.conf
        line: server ntp.aliyun.com iburst
      when: chronyd.rc == 0 and 'server ntp.aliyun.com iburst' not in chrony_conf.stdout
    - shell: |
        systemctl stop chronyd
        iptables -A OUTPUT -p udp -m udp -m multiport --dports 123 -m state --state NEW -j ACCEPT
        iptables -A INPUT -m state --state NEW -p udp --dport 123 -j ACCEPT
        chronyd -q 'server ntp.aliyun.com iburst'
        systemctl start chronyd
      when: chronyd.rc == 0 and 'server ntp.aliyun.com iburst' not in chrony_conf.stdout

- name: OS Network
  hosts: k8s_cluster
  gather_facts: False
  tasks:
    # Increase MTU for better performance
    - name: Change MTU to 9000 
      shell: ip link set dev eth0 mtu 9000
    - name: TCP fast open
      shell: sysctl -w net.ipv4.tcp_fastopen=3
  tags:
    - never
    - network
  

# Upgrade Kernel
- name: Upgrade Kernel
  hosts: k8s_cluster
  gather_facts: False
  tasks:
    - name: Update ELRepo Repository
      shell: |
        dnf update -y
        dnf install -y https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
        rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
        dnf makecache
      when: ansible_kernel | version('5.10','<')
    - name: Upgrade Kernel
      shell: |
        dnf --enablerepo="elrepo-kernel" install -y kernel-ml
      when: ansible_kernel | version('5.10','<')
    - name: Reboot the machine
      reboot:
        reboot_timeout: 300
      when: ansible_kernel | version('5.10','<')
    - name: Confirm kernel version
      shell: uname -a
      register: kernel_version
    - debug: var=kernel_version.stdout
  tags:
    - never
    - upgrade-kernel

- name: Install kernel-modules-extra since chaos-mesh depends it
  dnf:
    name: kernel-modules-extra
    state: present
  tags:
    - upgrade-kernel