apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: jenkins
    kubernetes.io/metadata.name: jenkins-cd
  name: jenkins-cd
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: jenkins
    kubernetes.io/metadata.name: jenkins-ticdc
  name: jenkins-ticdc
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: jenkins
    kubernetes.io/metadata.name: jenkins-tidb
  name: jenkins-tidb
