# see roles/network_plugin/cilium/defaults/main.yml

# cilium_version: "v1.11.3"
# cilium_identity_allocation_mode: kvstore # kvstore or crd

# For adding and mounting extra volumes to the cilium operator
# cilium_operator_extra_volumes: []
# cilium_operator_extra_volume_mounts: []

# Name of the cluster. Only relevant when building a mesh of clusters.
# cilium_cluster_name: default

# Unique ID of the cluster. Must be unique across all conneted clusters and
# in the range of 1 and 255. Only relevant when building a mesh of clusters.
# This value is not defined by default
# cluster-id:

# Allows to explicitly specify the IPv4 CIDR for native routing.
# When specified, Cilium assumes networking for this CIDR is preconfigured and
# hands traffic destined for that range to the Linux network stack without
# applying any SNAT.
# Generally speaking, specifying a native routing CIDR implies that Cilium can
# depend on the underlying networking stack to route packets to their
# destination. To offer a concrete example, if Cilium is configured to use
# direct routing and the Kubernetes CIDR is included in the native routing CIDR,
# the user must configure the routes to reach pods, either manually or by
# setting the auto-direct-node-routes flag.
# cilium_native_routing_cidr: ""

# Allows to explicitly specify the IPv6 CIDR for native routing.
# cilium_native_routing_cidr_ipv6: ""

# Encryption
# Enable transparent network encryption.
# cilium_encryption_enabled: false

# Encryption method. Can be either ipsec or wireguard.
# Only effective when `cilium_encryption_enabled` is set to true.
# cilium_encryption_type: "ipsec"

# Enable encryption for pure node to node traffic.
# This option is only effective when `cilium_encryption_type` is set to `ipsec`.
# cilium_ipsec_node_encryption: "false"

# Enables the fallback to the user-space implementation.
# This option is only effective when `cilium_encryption_type` is set to `wireguard`.
# cilium_wireguard_userspace_fallback: "false"

# Install Cilium Hubble
# cilium_enable_hubble: true ## enable support hubble in cilium
# cilium_hubble_install: true ## install hubble-relay, hubble-ui
# cilium_hubble_tls_generate: true ## install hubble-certgen and generate certificates
# cilium_enable_hubble_metrics: true
# cilium_hubble_metrics:
#   - dns
#   - drop
#   - tcp
#   - flow
#   - icmp
#   - http

cilium_enable_prometheus: true
cilium_preallocate_bpf_maps: true

# For higher version kernel
# cilium_tunnel_mode: disabled
cilium_ip_masq_agent_enable: false       # kernel >= 4.19
cilium_non_masquerade_cidrs:
  - 10.0.0.0/8
  # - 172.16.0.0/12 # IDC uses this CIDR
  - 192.168.0.0/16
  - 100.64.0.0/10
  - 192.0.0.0/24
  - 192.0.2.0/24
  - 192.88.99.0/24
  - 198.18.0.0/15
  - 198.51.100.0/24
  - 203.0.113.0/24
  - 240.0.0.0/4
# cilium_auto_direct_node_routes: true
# cilium_native_routing_cidr: 10.2.101.222/24
cilium_config_extra_vars: {
  # "install-no-conntrack-iptables-rules": true
  enable-host-reachable-services: false,  # kernel >= 4.19.57, >= 5.1.16, >= 5.2
  enable-bandwidth-manager: false,        # kernel >= 5.1
  enable-bpf-masquerade: false,           # kernel >= 4.19
  # custom-calls
  enable-remote-node-identity: true,
  enable-custom-calls: true
}

cilium_image_repo: "{{ docker_image_repo }}/cilium/cilium"
cilium_init_image_repo: "{{ docker_image_repo }}/cilium/cilium-init"
cilium_operator_image_repo: "{{ docker_image_repo }}/cilium/operator"
